// === 운전면허 3종 ===
  '1종운전면허(대형)': {
    name: '1종운전면허(대형)',
    icon: 'fa-car',
    category: '교통·운전',
    heroTitle: '2026년도 1종운전면허(대형) 합격 가이드',
    heroDesc: '1종 대형 운전면허는 버스·트럭·특수차량 등 대형 차량을 운전할 수 있는 자격입니다. 도로교통공단(KoRoad) 시험장에서 상시 접수·응시가 가능하며, 학과→기능→도로주행 3단계를 순차적으로 통과해야 합니다. 대중교통·물류·건설 분야 취업에 필수적인 자격으로 취득 후 활용 범위가 넓습니다.',
    passRateSummary: '학과 55~65% | 기능+도로 50~60%',
    avgPassRate: '57%',
    passRates: [
      { year: 2020, written: 58, practical: 52 },
      { year: 2021, written: 60, practical: 53 },
      { year: 2022, written: 62, practical: 55 },
      { year: 2023, written: 63, practical: 57 },
      { year: 2024, written: 65, practical: 59 },
    ],
    schedules: [
      { round: '상시', writtenExam: '연중 상시 접수·시험', writtenResult: '당일 발표', practicalExam: '학과 합격 후 즉시 예약', practicalResult: '당일 발표' },
    ],
    milestones: [
      { label: '학과시험 접수', date: '2026-01-01' },
      { label: '학과시험', date: '2026-01-07' },
      { label: '기능시험', date: '2026-01-14' },
      { label: '도로주행', date: '2026-01-21' },
    ],
    subjects: [
      { name: '교통법규', desc: '도로교통법, 신호·표지 이해' },
      { name: '자동차 구조', desc: '엔진·제동·조향 장치 기초 지식' },
      { name: '안전운전', desc: '긴급 상황 대처 및 방어운전' },
      { name: '기능시험', desc: '차로 변경·주차·경사로 출발 등 코스 주행' },
      { name: '도로주행', desc: '실제 도로에서 규정 준수 및 안전 운전 평가' },
    ],
    jobs: [
      { title: '버스 운전기사', company: '시내버스·고속버스 운수회사', salary: '3,000~4,500만원', location: '전국', type: '정규직' },
      { title: '화물차 기사', company: '물류·운송회사', salary: '3,500~5,000만원', location: '전국', type: '정규직' },
      { title: '굴절차량 운전원', company: '굴절버스 운수회사', salary: '3,200~4,200만원', location: '수도권', type: '정규직' },
      { title: '특수차량 운전원', company: '건설·중장비 업체', salary: '3,500~5,500만원', location: '전국', type: '정규직' },
      { title: '대형 트럭 운전기사', company: '택배·물류 대기업', salary: '4,000~5,500만원', location: '전국', type: '정규직' },
    ],
    books: [
      { title: '2026 운전면허 학과시험 총정리 (1·2종 공통)', author: '도로교통공단', publisher: '도로교통공단', year: 2025, rating: 4.7 },
      { title: '운전면허 1종 대형 핵심 요약집', author: '카스쿨 편집부', publisher: '카스쿨', year: 2025, rating: 4.4 },
      { title: '2026 한번에 합격하는 운전면허 학과 문제집', author: '이패스코리아 편집부', publisher: '이패스코리아', year: 2025, rating: 4.5 },
      { title: '운전면허 시험장 기능코스 완전정복', author: '드라이브 편집부', publisher: '길벗', year: 2024, rating: 4.3 },
    ],
    defaultTodos: [
      '학과 문제집 1회독 (교통법규 집중)',
      '문제은행 앱으로 모의시험 반복 (목표: 80점 이상)',
      '기능시험 코스 숙지 (경사로·굴절·직각 주차)',
      '도로주행 연습 (방향지시등·속도 조절 체크)',
      '시험장 사전 답사 및 예약 확인',
    ],
  },
  '1종운전면허(보통)': {
    name: '1종운전면허(보통)',
    icon: 'fa-car',
    category: '교통·운전',
    heroTitle: '2026년도 1종운전면허(보통) 합격 가이드',
    heroDesc: '1종 보통 운전면허는 승용차와 15인 이하 승합차, 적재중량 12톤 미만 화물차 등을 운전할 수 있는 자격입니다. 도로교통공단(KoRoad) 시험장에서 상시 접수·응시가 가능하며 직업 운전직 취업 시 가장 널리 요구되는 면허입니다. 택시·화물·렌터카 등 운수업 종사를 희망하는 분에게 필수 자격증입니다.',
    passRateSummary: '학과 60~70% | 기능+도로 55~65%',
    avgPassRate: '62%',
    passRates: [
      { year: 2020, written: 62, practical: 57 },
      { year: 2021, written: 64, practical: 59 },
      { year: 2022, written: 66, practical: 61 },
      { year: 2023, written: 68, practical: 63 },
      { year: 2024, written: 70, practical: 65 },
    ],
    schedules: [
      { round: '상시', writtenExam: '연중 상시 접수·시험', writtenResult: '당일 발표', practicalExam: '학과 합격 후 즉시 예약', practicalResult: '당일 발표' },
    ],
    milestones: [
      { label: '학과시험 접수', date: '2026-01-01' },
      { label: '학과시험', date: '2026-01-07' },
      { label: '기능시험', date: '2026-01-14' },
      { label: '도로주행', date: '2026-01-21' },
    ],
    subjects: [
      { name: '교통법규', desc: '도로교통법, 신호·표지 이해' },
      { name: '자동차 구조', desc: '엔진·제동·조향 장치 기초 지식' },
      { name: '안전운전', desc: '긴급 상황 대처 및 방어운전' },
      { name: '기능시험', desc: '차로 변경·주차·경사로 출발 등 코스 주행' },
      { name: '도로주행', desc: '실제 도로에서 규정 준수 및 안전 운전 평가' },
    ],
    jobs: [
      { title: '택시 운전사', company: '개인·법인 택시 회사', salary: '3,000~4,000만원', location: '전국', type: '정규직' },
      { title: '화물차 기사', company: '중소 운송·물류회사', salary: '3,200~4,500만원', location: '전국', type: '정규직' },
      { title: '렌터카 드라이버', company: '렌터카·카셰어링 업체', salary: '2,800~3,800만원', location: '전국', type: '정규직' },
      { title: '셔틀버스 운전기사', company: '기업·학교·공공기관', salary: '2,800~3,500만원', location: '전국', type: '정규직' },
      { title: '대리운전 기사', company: '대리운전 플랫폼', salary: '2,500~4,000만원', location: '전국', type: '프리랜서' },
    ],
    books: [
      { title: '2026 운전면허 학과시험 총정리 (1·2종 공통)', author: '도로교통공단', publisher: '도로교통공단', year: 2025, rating: 4.7 },
      { title: '2026 한번에 합격하는 운전면허 학과 문제집', author: '이패스코리아 편집부', publisher: '이패스코리아', year: 2025, rating: 4.5 },
      { title: '운전면허 1종 보통 30일 완성', author: '카드라이브 편집부', publisher: '성안당', year: 2025, rating: 4.4 },
      { title: '운전면허 시험장 기능코스 완전정복', author: '드라이브 편집부', publisher: '길벗', year: 2024, rating: 4.3 },
    ],
    defaultTodos: [
      '학과 문제집 1회독 (교통법규 집중)',
      '문제은행 앱으로 모의시험 반복 (목표: 80점 이상)',
      '기능시험 코스 숙지 (경사로·굴절·직각 주차)',
      '도로주행 연습 (방향지시등·속도 조절 체크)',
      '시험장 사전 답사 및 예약 확인',
    ],
  },
  '2종운전면허(보통)': {
    name: '2종운전면허(보통)',
    icon: 'fa-car',
    category: '교통·운전',
    heroTitle: '2026년도 2종운전면허(보통) 합격 가이드',
    heroDesc: '2종 보통 운전면허는 승용차와 10인 이하 승합차, 적재중량 4톤 이하 화물차를 운전할 수 있는 가장 기본적인 운전 자격입니다. 도로교통공단(KoRoad) 시험장에서 상시 접수·응시가 가능하며, 1종에 비해 시험 난이도가 낮아 일반인이 가장 많이 취득하는 면허입니다. 취업·생활 전반에서 폭넓게 활용되는 필수 생활 자격증입니다.',
    passRateSummary: '학과 65~75% | 기능+도로 60~70%',
    avgPassRate: '68%',
    passRates: [
      { year: 2020, written: 67, practical: 62 },
      { year: 2021, written: 69, practical: 64 },
      { year: 2022, written: 71, practical: 65 },
      { year: 2023, written: 73, practical: 67 },
      { year: 2024, written: 75, practical: 69 },
    ],
    schedules: [
      { round: '상시', writtenExam: '연중 상시 접수·시험', writtenResult: '당일 발표', practicalExam: '학과 합격 후 즉시 예약', practicalResult: '당일 발표' },
    ],
    milestones: [
      { label: '학과시험 접수', date: '2026-01-01' },
      { label: '학과시험', date: '2026-01-07' },
      { label: '기능시험', date: '2026-01-14' },
      { label: '도로주행', date: '2026-01-21' },
    ],
    subjects: [
      { name: '교통법규', desc: '도로교통법, 신호·표지 이해' },
      { name: '자동차 구조', desc: '엔진·제동·조향 장치 기초 지식' },
      { name: '안전운전', desc: '긴급 상황 대처 및 방어운전' },
      { name: '기능시험', desc: '차로 변경·주차·경사로 출발 등 코스 주행' },
      { name: '도로주행', desc: '실제 도로에서 규정 준수 및 안전 운전 평가' },
    ],
    jobs: [
      { title: '배달 드라이버', company: '쿠팡·마켓컬리 등 물류 플랫폼', salary: '2,800~4,000만원', location: '전국', type: '계약직' },
      { title: '영업용 차량 운전기사', company: '중소기업·유통회사', salary: '2,800~3,800만원', location: '전국', type: '정규직' },
      { title: '카셰어링 관리원', company: '카셰어링·렌터카 업체', salary: '2,500~3,200만원', location: '전국', type: '정규직' },
      { title: '사설 구급차 운전원', company: '사설 응급 이송업체', salary: '3,000~4,000만원', location: '전국', type: '정규직' },
      { title: '경비·시설 관리원', company: '아파트·건물 관리업체', salary: '2,400~3,200만원', location: '전국', type: '정규직' },
    ],
    books: [
      { title: '2026 운전면허 학과시험 총정리 (1·2종 공통)', author: '도로교통공단', publisher: '도로교통공단', year: 2025, rating: 4.7 },
      { title: '2026 한번에 합격하는 운전면허 학과 문제집', author: '이패스코리아 편집부', publisher: '이패스코리아', year: 2025, rating: 4.5 },
      { title: '운전면허 2종 보통 단기 합격 비법', author: '자동차생활 편집부', publisher: '성안당', year: 2025, rating: 4.4 },
      { title: '운전면허 시험장 기능코스 완전정복', author: '드라이브 편집부', publisher: '길벗', year: 2024, rating: 4.3 },
    ],
    defaultTodos: [
      '학과 문제집 1회독 (교통법규 집중)',
      '문제은행 앱으로 모의시험 반복 (목표: 80점 이상)',
      '기능시험 코스 숙지 (경사로·굴절·직각 주차)',
      '도로주행 연습 (방향지시등·속도 조절 체크)',
      '시험장 사전 답사 및 예약 확인',
    ],
  },
