// === 자동차 그룹1 5종 ===
  '이륜자동차운전면허': {
    name: '이륜자동차운전면허',
    icon: 'fa-motorcycle',
    category: '교통·운전',
    heroTitle: '2026년도 이륜자동차운전면허 합격 가이드',
    heroDesc: '이륜자동차운전면허는 오토바이·스쿠터 등 이륜차를 합법적으로 운행하기 위해 필수적인 면허입니다. 학과시험과 기능시험으로 구성되며, 운전면허시험장에서 상시 접수 및 응시가 가능합니다. 배달·물류 종사자부터 레저 라이더까지 폭넓게 활용되는 자격입니다.',
    passRateSummary: '학과 70% | 기능 65%',
    avgPassRate: '68%',
    passRates: [
      { year: 2020, written: 68, practical: 63 },
      { year: 2021, written: 70, practical: 64 },
      { year: 2022, written: 71, practical: 65 },
      { year: 2023, written: 69, practical: 66 },
      { year: 2024, written: 70, practical: 65 },
    ],
    schedules: [
      { round: '상시', writtenExam: '연중 상시 접수·시험', writtenResult: '당일 발표', practicalExam: '학과 합격 후 즉시 예약', practicalResult: '당일 발표' },
    ],
    milestones: [
      { label: '학과 응시', date: '2026-01-05' },
      { label: '기능 응시', date: '2026-01-12' },
      { label: '도로주행', date: '2026-01-19' },
      { label: '면허 취득', date: '2026-01-20' },
    ],
    subjects: [
      { name: '교통법규', desc: '도로교통법 및 이륜차 관련 법규 이해' },
      { name: '안전운전', desc: '이륜차 안전 운행 요령 및 방어운전 기술' },
      { name: '도로주행', desc: '실제 도로 환경에서의 이륜차 조작 및 주행' },
      { name: '기초기능', desc: '이륜차 발진·정지·방향 전환 등 기본 조작' },
      { name: '이륜차 구조', desc: '이륜차 기본 구조 및 점검 요령' },
    ],
    jobs: [
      { title: '배달라이더', company: '배달 플랫폼', salary: '3,000~4,500만원', location: '전국', type: '계약직' },
      { title: '퀵서비스 기사', company: '물류·배송업체', salary: '3,000~4,000만원', location: '수도권', type: '정규직' },
      { title: '이륜차 강사', company: '운전면허학원', salary: '3,500~4,500만원', location: '전국', type: '정규직' },
      { title: '이륜차 정비원', company: '이륜차 정비소', salary: '3,000~4,000만원', location: '전국', type: '정규직' },
      { title: '우편집배원', company: '우체국·공공기관', salary: '3,200~4,200만원', location: '전국', type: '정규직' },
    ],
    books: [
      { title: '이륜자동차 운전면허 학과시험 총정리', author: '도로교통공단', publisher: '도로교통공단', year: 2024, rating: 4.5 },
      { title: '이륜차 면허 기출문제 완전정복', author: '면허연구회', publisher: '성안당', year: 2024, rating: 4.4 },
      { title: '이륜자동차 안전운전 가이드', author: '김안전', publisher: '일진사', year: 2023, rating: 4.3 },
      { title: '오토바이 면허 한 번에 합격하기', author: '박합격', publisher: '크라운출판사', year: 2024, rating: 4.2 },
    ],
    defaultTodos: [
      '도로교통법 이륜차 관련 조항 집중 학습',
      '학과시험 기출문제 반복 풀이',
      '기초 기능 코스 연습 (굴절·곡선·연속진로전환)',
      '실제 도로 상황 대비 안전운전 요령 숙지',
      '최근 기출 문제 1회분 실전 조건으로 풀고 오답 분석',
    ],
  },
  '자동차정비기사': {
    name: '자동차정비기사',
    icon: 'fa-car-wrench',
    category: '기계·설비',
    heroTitle: '2026년도 자동차정비기사 합격 가이드',
    heroDesc: '자동차정비기사는 자동차의 엔진, 섀시, 전기장치 등 전반적인 정비 및 점검 능력을 검증하는 국가기술자격입니다. 자동차 딜러사 서비스센터, 자동차검사소, 독립 정비업체 등 다양한 분야에서 활발히 활용됩니다. 기계·전기 융합 지식이 요구되며 취업 및 창업 경쟁력을 높이는 핵심 자격입니다.',
    passRateSummary: '필기 45% | 실기 55%',
    avgPassRate: '50%',
    passRates: [
      { year: 2020, written: 43, practical: 52 },
      { year: 2021, written: 45, practical: 54 },
      { year: 2022, written: 47, practical: 56 },
      { year: 2023, written: 44, practical: 55 },
      { year: 2024, written: 46, practical: 57 },
    ],
    schedules: [
      { round: '1회', writtenExam: '2026-01-19 ~ 2026-01-22', writtenResult: '2026-02-12', practicalExam: '2026-03-23 ~ 2026-04-05', practicalResult: '2026-04-18' },
      { round: '2회', writtenExam: '2026-04-13 ~ 2026-04-16', writtenResult: '2026-05-07', practicalExam: '2026-06-28 ~ 2026-07-12', practicalResult: '2026-07-24' },
      { round: '3회', writtenExam: '2026-07-27 ~ 2026-07-30', writtenResult: '2026-08-20', practicalExam: '2026-10-04 ~ 2026-10-17', practicalResult: '2026-11-06' },
    ],
    milestones: [
      { label: '1회 필기', date: '2026-01-19' },
      { label: '1회 실기', date: '2026-03-23' },
      { label: '2회 필기', date: '2026-04-13' },
      { label: '2회 실기', date: '2026-06-28' },
    ],
    subjects: [
      { name: '자동차엔진정비', desc: '엔진 구조 원리, 고장 진단 및 정비 방법' },
      { name: '자동차섀시정비', desc: '동력전달장치, 현가장치, 제동장치 구조 및 정비' },
      { name: '자동차전기·전자장치정비', desc: '전기회로, 전자제어 시스템 진단 및 수리' },
      { name: '자동차차체정비', desc: '차체 구조, 판금·도장 및 안전기준' },
      { name: '자동차정비검사', desc: '법정 정기검사 기준 및 검사 방법론' },
    ],
    jobs: [
      { title: '자동차정비기사', company: '완성차 딜러 서비스센터', salary: '4,000~5,500만원', location: '전국', type: '정규직' },
      { title: '정비팀장', company: '자동차 정비업체', salary: '4,500~6,000만원', location: '수도권', type: '정규직' },
      { title: '자동차검사원', company: '자동차검사소', salary: '3,800~5,000만원', location: '전국', type: '정규직' },
      { title: '기술지원 엔지니어', company: '자동차부품 제조사', salary: '4,200~5,500만원', location: '수도권·충청', type: '정규직' },
      { title: '자동차정비 강사', company: '직업훈련기관', salary: '3,500~4,500만원', location: '전국', type: '계약직' },
    ],
    books: [
      { title: '자동차정비기사 필기 완전정복', author: '이정비', publisher: '성안당', year: 2024, rating: 4.5 },
      { title: '자동차정비기사 실기 실전문제', author: '박엔진', publisher: '일진사', year: 2024, rating: 4.4 },
      { title: '자동차정비기사 기출문제 총정리', author: '자동차정비연구회', publisher: '성안당', year: 2023, rating: 4.3 },
      { title: '자동차 엔진·섀시·전기 핵심이론', author: '김기사', publisher: '크라운출판사', year: 2024, rating: 4.2 },
    ],
    defaultTodos: [
      '필기 시험 범위 파악 및 출제 경향 분석',
      '엔진·섀시·전기장치 핵심 이론 정리',
      '기출문제 풀이 (최근 3개년)',
      '실기 장비 점검 및 진단 실습',
      '최근 5개년 기출문제 1회분 실전 조건으로 풀고 오답 분석',
    ],
  },
  '자동차정비산업기사': {
    name: '자동차정비산업기사',
    icon: 'fa-car-wrench',
    category: '기계·설비',
    heroTitle: '2026년도 자동차정비산업기사 합격 가이드',
    heroDesc: '자동차정비산업기사는 자동차 각 장치의 점검·진단·정비 능력을 평가하는 국가기술자격으로, 기능사보다 심화된 이론과 실무 능력이 요구됩니다. 정비업체, 검사소, 완성차 서비스센터 등에서 중간 관리 및 전문 기술직으로 활약할 수 있습니다. 기사 자격 취득을 위한 디딤돌로도 널리 활용됩니다.',
    passRateSummary: '필기 50% | 실기 55%',
    avgPassRate: '52%',
    passRates: [
      { year: 2020, written: 46, practical: 51 },
      { year: 2021, written: 48, practical: 53 },
      { year: 2022, written: 51, practical: 56 },
      { year: 2023, written: 50, practical: 55 },
      { year: 2024, written: 52, practical: 57 },
    ],
    schedules: [
      { round: '1회', writtenExam: '2026-01-19 ~ 2026-01-22', writtenResult: '2026-02-12', practicalExam: '2026-03-23 ~ 2026-04-05', practicalResult: '2026-04-18' },
      { round: '2회', writtenExam: '2026-04-13 ~ 2026-04-16', writtenResult: '2026-05-07', practicalExam: '2026-06-28 ~ 2026-07-12', practicalResult: '2026-07-24' },
      { round: '3회', writtenExam: '2026-07-27 ~ 2026-07-30', writtenResult: '2026-08-20', practicalExam: '2026-10-04 ~ 2026-10-17', practicalResult: '2026-11-06' },
    ],
    milestones: [
      { label: '1회 필기', date: '2026-01-19' },
      { label: '1회 실기', date: '2026-03-23' },
      { label: '2회 필기', date: '2026-04-13' },
      { label: '2회 실기', date: '2026-06-28' },
    ],
    subjects: [
      { name: '자동차엔진', desc: '엔진 주요 구성요소의 구조·작동 원리 및 정비' },
      { name: '자동차섀시', desc: '조향·제동·현가 장치의 구조 원리 및 점검 정비' },
      { name: '자동차전기', desc: '충전·시동·등화 회로 및 전자제어 시스템 정비' },
      { name: '자동차정비', desc: '각 장치별 분해·조립·측정 및 수리 실무' },
      { name: '안전관리', desc: '정비 작업 중 산업안전 및 환경 법규 준수' },
    ],
    jobs: [
      { title: '자동차정비 기술원', company: '자동차 정비업체', salary: '3,500~4,800만원', location: '전국', type: '정규직' },
      { title: '서비스 어드바이저', company: '완성차 딜러사', salary: '3,800~5,000만원', location: '수도권', type: '정규직' },
      { title: '자동차검사원', company: '자동차검사소', salary: '3,500~4,500만원', location: '전국', type: '정규직' },
      { title: '정비기술 지원', company: '자동차부품 제조사', salary: '3,800~5,000만원', location: '수도권·경기', type: '정규직' },
      { title: '자동차정비 교육강사', company: '직업능력개발원', salary: '3,200~4,200만원', location: '전국', type: '계약직' },
    ],
    books: [
      { title: '자동차정비산업기사 필기 단기완성', author: '최정비', publisher: '성안당', year: 2024, rating: 4.5 },
      { title: '자동차정비산업기사 실기 실전정복', author: '이섀시', publisher: '일진사', year: 2024, rating: 4.4 },
      { title: '자동차정비산업기사 기출문제집', author: '자동차기술연구회', publisher: '성안당', year: 2023, rating: 4.3 },
      { title: '자동차 전기·전자 핵심이론과 실기', author: '박전기', publisher: '크라운출판사', year: 2024, rating: 4.2 },
    ],
    defaultTodos: [
      '필기 시험 범위 파악 및 출제 경향 분석',
      '주요 과목 핵심 이론 정리',
      '기출문제 풀이 (최근 3개년)',
      '실기 장비 점검 및 진단 실습',
      '최근 5개년 기출문제 1회분 실전 조건으로 풀고 오답 분석',
    ],
  },
  '자동차정비기능장': {
    name: '자동차정비기능장',
    icon: 'fa-car-wrench',
    category: '기계·설비',
    heroTitle: '2026년도 자동차정비기능장 합격 가이드',
    heroDesc: '자동차정비기능장은 자동차 정비 분야 최고 등급의 국가기술자격으로, 고난이도 진단·정비 능력과 현장 지도 역량을 동시에 검증합니다. 합격률이 낮아 철저한 준비가 필요하며, 취득 후에는 정비소 개설·운영 및 기능 인력 지도·감독 역할을 수행할 수 있습니다. 자동차 정비 분야 최고 전문가로 인정받는 권위 있는 자격입니다.',
    passRateSummary: '필기 40% | 실기 45%',
    avgPassRate: '42%',
    passRates: [
      { year: 2020, written: 37, practical: 41 },
      { year: 2021, written: 39, practical: 43 },
      { year: 2022, written: 41, practical: 46 },
      { year: 2023, written: 38, practical: 44 },
      { year: 2024, written: 40, practical: 45 },
    ],
    schedules: [
      { round: '1회', writtenExam: '2026-01-19 ~ 2026-01-22', writtenResult: '2026-02-12', practicalExam: '2026-03-23 ~ 2026-04-05', practicalResult: '2026-04-18' },
      { round: '2회', writtenExam: '2026-04-13 ~ 2026-04-16', writtenResult: '2026-05-07', practicalExam: '2026-06-28 ~ 2026-07-12', practicalResult: '2026-07-24' },
      { round: '3회', writtenExam: '2026-07-27 ~ 2026-07-30', writtenResult: '2026-08-20', practicalExam: '2026-10-04 ~ 2026-10-17', practicalResult: '2026-11-06' },
    ],
    milestones: [
      { label: '1회 필기', date: '2026-01-19' },
      { label: '1회 실기', date: '2026-03-23' },
      { label: '2회 필기', date: '2026-04-13' },
      { label: '2회 실기', date: '2026-06-28' },
    ],
    subjects: [
      { name: '자동차엔진 고급정비', desc: '엔진 전자제어 시스템 심화 진단 및 오버홀' },
      { name: '자동차섀시 고급정비', desc: '자동변속기, ABS, 전자식 현가장치 정밀 정비' },
      { name: '자동차전기·전자 고급정비', desc: 'CAN 통신, 첨단 안전장치(ADAS) 진단 및 수리' },
      { name: '자동차 작업관리', desc: '현장 지도·감독, 작업 표준 수립 및 품질 관리' },
      { name: '안전·환경관리', desc: '고전압 전기차 안전 작업 및 폐기물 처리 기준' },
    ],
    jobs: [
      { title: '정비소 소장·기술이사', company: '자동차 정비업체', salary: '5,000~7,000만원', location: '전국', type: '정규직' },
      { title: '완성차 서비스 마스터', company: '완성차 딜러사', salary: '5,500~7,500만원', location: '수도권', type: '정규직' },
      { title: '자동차검사 수석검사원', company: '자동차검사소', salary: '4,500~6,000만원', location: '전국', type: '정규직' },
      { title: '기술훈련 교수', company: '직업능력개발원·폴리텍대', salary: '4,800~6,500만원', location: '전국', type: '정규직' },
      { title: '자동차 기술 컨설턴트', company: '자동차 컨설팅사', salary: '5,000~8,000만원', location: '수도권', type: '계약직' },
    ],
    books: [
      { title: '자동차정비기능장 필기 완전정복', author: '이마스터', publisher: '성안당', year: 2024, rating: 4.5 },
      { title: '자동차정비기능장 실기 핵심정복', author: '박기능장', publisher: '일진사', year: 2024, rating: 4.4 },
      { title: '자동차정비기능장 20개년 기출문제', author: '자동차고급정비연구회', publisher: '성안당', year: 2023, rating: 4.3 },
      { title: '자동차 전자제어 시스템 심화이론', author: '김전자', publisher: '골든벨', year: 2024, rating: 4.2 },
    ],
    defaultTodos: [
      '필기 시험 범위 파악 및 출제 경향 분석',
      '전자제어·CAN통신 등 심화 이론 집중 정리',
      '기출문제 풀이 (최근 5개년)',
      '오버홀·정밀 진단 실기 집중 실습',
      '최근 5개년 기출문제 1회분 실전 조건으로 풀고 오답 분석',
    ],
  },
  '자동차정비기능사': {
    name: '자동차정비기능사',
    icon: 'fa-car-wrench',
    category: '기계·설비',
    heroTitle: '2026년도 자동차정비기능사 합격 가이드',
    heroDesc: '자동차정비기능사는 자동차 정비 입문 단계의 국가기술자격으로, 기본적인 점검·정비 실무 능력을 인증합니다. 자동차 정비업 취업의 첫 관문으로 활용도가 높으며, 이후 산업기사·기사로 상위 자격 취득의 발판이 됩니다. 비교적 합격률이 높아 체계적인 준비로 단기 취득이 가능합니다.',
    passRateSummary: '필기 60% | 실기 60%',
    avgPassRate: '60%',
    passRates: [
      { year: 2020, written: 57, practical: 57 },
      { year: 2021, written: 59, practical: 59 },
      { year: 2022, written: 62, practical: 61 },
      { year: 2023, written: 60, practical: 60 },
      { year: 2024, written: 61, practical: 62 },
    ],
    schedules: [
      { round: '1회', writtenExam: '2026-01-19 ~ 2026-01-22', writtenResult: '2026-02-12', practicalExam: '2026-03-23 ~ 2026-04-05', practicalResult: '2026-04-18' },
      { round: '2회', writtenExam: '2026-04-13 ~ 2026-04-16', writtenResult: '2026-05-07', practicalExam: '2026-06-28 ~ 2026-07-12', practicalResult: '2026-07-24' },
      { round: '3회', writtenExam: '2026-07-27 ~ 2026-07-30', writtenResult: '2026-08-20', practicalExam: '2026-10-04 ~ 2026-10-17', practicalResult: '2026-11-06' },
    ],
    milestones: [
      { label: '1회 필기', date: '2026-01-19' },
      { label: '1회 실기', date: '2026-03-23' },
      { label: '2회 필기', date: '2026-04-13' },
      { label: '2회 실기', date: '2026-06-28' },
    ],
    subjects: [
      { name: '자동차엔진', desc: '엔진 기본 구조와 작동 원리, 기초 점검 방법' },
      { name: '자동차섀시', desc: '제동·현가·조향 장치 기초 구조 및 점검' },
      { name: '자동차전기', desc: '기본 전기회로, 배터리·시동·충전 장치 점검' },
      { name: '자동차정비실무', desc: '오일·필터 교환, 소모품 교체 등 기초 정비 작업' },
      { name: '안전관리', desc: '정비 작업 안전수칙 및 공구·장비 올바른 사용법' },
    ],
    jobs: [
      { title: '자동차정비 기능원', company: '자동차 정비소', salary: '2,800~3,800만원', location: '전국', type: '정규직' },
      { title: '서비스 테크니션', company: '완성차 딜러 서비스센터', salary: '3,000~4,000만원', location: '전국', type: '정규직' },
      { title: '자동차검사 보조원', company: '자동차검사소', salary: '2,800~3,500만원', location: '전국', type: '정규직' },
      { title: '정비실습 조교', company: '직업훈련기관·고등학교', salary: '2,800~3,500만원', location: '전국', type: '정규직' },
      { title: '자동차 부품 관리원', company: '자동차부품 유통업체', salary: '2,600~3,400만원', location: '수도권', type: '계약직' },
    ],
    books: [
      { title: '자동차정비기능사 필기 단기합격', author: '김기능', publisher: '성안당', year: 2024, rating: 4.5 },
      { title: '자동차정비기능사 실기 완전정복', author: '이정비', publisher: '일진사', year: 2024, rating: 4.4 },
      { title: '자동차정비기능사 과년도 기출문제', author: '자동차정비연구회', publisher: '성안당', year: 2023, rating: 4.3 },
      { title: '자동차 기초정비 입문서', author: '박입문', publisher: '골든벨', year: 2024, rating: 4.2 },
    ],
    defaultTodos: [
      '필기 시험 범위 파악 및 출제 경향 분석',
      '주요 과목 핵심 이론 정리',
      '기출문제 풀이 (최근 3개년)',
      '실기 장비 점검 및 진단 실습',
      '최근 5개년 기출문제 1회분 실전 조건으로 풀고 오답 분석',
    ],
  },
